version: "3.7"
services:
  php:
    build:
      args:
        user: joshua
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      #- ./docker-compose/php_config:/usr/local/etc/php
    networks:
      - googlelogin

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      - googlelogin:/var/lib/mysql
    networks:
      - googlelogin

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - googlelogin

  rabbit:
    image: "rabbitmq:3-management"
    hostname: "${RABBITMQ_HOST_NAME}"
    environment:
      #RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASSWORD}"
      #RABBITMQ_DEFAULT_HOST: "${RABBITMQ_HOST}"
      RABBITMQ_DEFAULT_VHOST: "${RABBITMQ_VHOST}"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "${RABBITMQ_NAME}"
    volumes:
      #- "./docker-compose/rabbitmq:/etc/rabbitmq/enabled_plugins/"
      - "./docker-compose/rabbitmq:/var/log/rabbitmq"
    networks:
      - googlelogin

networks:
  googlelogin:

volumes:
  googlelogin: